[SDK-751] update sample apps readme and root readme
skyflowapi/skyflow-node pull request #56
Opened 2022-09-22 08:22 UTC by skyflow-puneet

Signed-off-by: skyflow-puneet <puneet.verma@skyflow.com>

2022-09-23 09:09 UTC, Shaik-Luqmaan commented on samples/README.md
> +Use this folder to test the functionalities of JAVA-SDK just by adding `VAULT-ID` `VAULT-URL` and `SERVICE-ACCOUNT` details at the required place.
Use this folder to test the functionalities of Node-SDK and Java SDK

2022-10-17 13:05 UTC, Shaik-Luqmaan approved these changes

2022-10-19 19:23 UTC, manny-silva requested changes

2022-10-19 19:23 UTC, manny-silva commented on samples/README.md
> +# NODE-SDK sample templates
Make changes to match comments in the parallel Python SDK PR: https://github.com/skyflowapi/skyflow-python/pull/64

2023-02-08 12:13 UTC, yaswanth-pula-skyflow approved these changes

2025-06-10 14:39 UTC, closed without merging