SDK-774 update readme to provide es module import usage
skyflowapi/skyflow-node pull request #57
Opened 2022-09-29 14:12 UTC by yaswanth-pula-skyflow

2022-09-29 16:14 UTC, thefalc commented on README.md
> +#### Or using ES modules
Remove the #### and just have Or using ES modules: as regular text.

2022-09-29 16:15 UTC, thefalc requested changes
Small change

2022-09-30 10:52 UTC, yaswanth-pula-skyflow commented on README.md
> +#### Or using ES modules
Sure, added as regular text

2022-09-30 10:59 UTC, Shaik-Luqmaan approved these changes

2022-09-30 10:59 UTC, merged